# Generated by Django 4.0.1 on 2024-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('license_expiry', models.DateField()),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('emergency_n', models.CharField(max_length=100)),
                ('emergency_no', models.CharField(max_length=15)),
                ('blood_grp', models.CharField(max_length=5)),
                ('medical_history', models.TextField()),
                ('allergies', models.TextField()),
                ('current_med', models.BooleanField(default=False)),
                ('addiction', models.TextField()),
                ('occupation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=50)),
                ('dp', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_visited', models.CharField(max_length=255, unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
