# Generated by Django 4.0.1 on 2024-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_email', models.CharField(max_length=200)),
                ('p_email', models.CharField(default=None, max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('specialization', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=10)),
                ('vc_link', models.TextField(default=None)),
                ('completed', models.BooleanField(default=False)),
                ('doc_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
