# Generated by Django 4.0.1 on 2024-09-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mails',
            old_name='date',
            new_name='datecreated',
        ),
    ]
