# Generated by Django 5.0.6 on 2024-09-28 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contactus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 28, 9, 16, 31, 922800, tzinfo=datetime.timezone.utc)),
        ),
    ]
