# Generated by Django 5.0.6 on 2024-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_date_mails_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='description',
            field=models.CharField(default=True, max_length=400),
        ),
        migrations.AddField(
            model_name='appointments',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
